DTSPO-4157 Use tagging module
hmcts/sds-toffee-recipes-service pull request #18
Opened 2021-09-06 13:37 UTC by mokainos

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

https://tools.hmcts.net/jira/browse/DTSPO-4157
### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x] No
```

2021-09-06 13:48 UTC, timja requested changes

2021-09-06 13:48 UTC, timja commented on infrastructure/main.tf
> -  common_tags        = var.common_tags
this is built via jenkins, any missing tags should be added to cnp-jenkins-library

2021-09-07 12:07 UTC, timja approved these changes

2021-09-07 13:18 UTC, mokainos commented
not required

2021-09-07 13:18 UTC, closed without merging